config/routes.rb
Rails.application.routes.draw do
  devise_for :profiles
  resources :friends
  get 'home/index'
  get 'home/about'
  get 'home/contact'


  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "home#index"
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :profile
end

app/models/profile.rb
class Profile < ApplicationRecord
  # Include default devise modules. Others available are:
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/favour_controller.rb
class FavourController < ApplicationController
    def index

     @name = 'Ativie Favour'

      if @name 
      @output = "Ativie Favour Emmanuel"
      end
    end

end
 

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_profile!, except: [:index]
  before_action :correct_user, only: [:edit, :update, :destroy, :show]

  # GET /friends or /friends.json
  def index
    if profile_signed_in?
    @friends = current_profile.friends
    end
    
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = current_profile.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
  
    @friend = current_profile.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was deleted."}
      format.json { head :no_content }
    end
  end


  def correct_user
    @friend = current_profile.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized to view this friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through to the controller.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :profile_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favour_helper.rb
module FavourHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_clicked.html.erb
<div id="<%= dom_id friend %>" class="card blue-grey darken-1 white-text">
<p>
<strong>Name: </strong>

<%= friend.first_name + " " + friend.last_name%>

</p>


  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
    
  </p>

</div>

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.number_field :phone %>
  </div>

  <div>
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter %>
  </div>

  <div>

    <%= form.number_field :profile_id, value:current_profile.id, id: :friend_profile_id, type: :hidden %>
  </div>

  <%= %>

  <div>
    <%= form.submit class: "waves-effect waves-light btn-small" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>" class="card blue-grey darken-1 white-text">
<p>
<strong>Name: </strong>

  <%= link_to friend.first_name + " " +  friend.last_name, friend_path(friend),style: "text-decoration: none; color: yellow; font-weight: bold" %>

</p>


  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

 

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class: "btn btn-secondary btn-sm mb-2"%> 
  <%= button_to "Delete", @friend, method: :delete, class: "btn btn-danger btn-sm mb-2" %> 
  <%= link_to "Back to friends", friends_path, class: "btn btn-secondary btn-sm mb-2" %>
</div>

app/views/friends/index.html.erb
<h1>Friends</h1>


<% if @friends.present? %>
  <% if @friends.empty? %>
    <p>Hey there <%= current_profile.email%>, You have no friends!! :(</p>
  <% else %>
    <% @friends.each do |friend| %>
      <% if friend.profile == current_profile %>
        <%= render friend %>
      <% end %>
    <% end %>
  <% end %>
<% else %>
  <%if profile_signed_in? %>
    <p>Hey there <%= current_profile.email%>, You have no friends!! :(</p>

    <%else%>
    <p>Cannot retrieve friends, please sign in</p>
  <%end%>

<% end %>

<%= link_to "New friend", new_friend_path %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/show.html.erb
<h3>Hey there <%= @friend.first_name %></h3>

<div >
  <div class="card-content">
    <p><strong>Firstname:</strong>  <%= @friend.first_name %></p>
    <p><strong>Lastname: </strong><%= @friend.last_name %></p>
    <p><strong> Email:</strong> <%= @friend.email %></p>
    <p><strong>Phone</strong> <%= @friend.phone %></p>
    <p><strong>Twitter: </strong> <%= @friend.twitter %></p>
  </div>

<div >
  <%= link_to "Edit this friend", edit_friend_path(@friend), class: "card-action"%>
  <%= link_to "Back to friends", friends_path, class: "card-action"%>

  <%= button_to "Destroy this friend", @friend, class: "waves-effect waves-light btn-small white-text", method: :delete, data: {confirm: "Are you sure?"} %>
</div>

</div>

app/views/home/about.html.erb
<h1>About page</h1>

app/views/home/contact.html.erb
<h1>Contact page</h1>

app/views/home/index.html.erb
<% if profile_signed_in? %>
<h1>Welcome <%= current_profile.email %></h1>
  <%else %>
  <p>Hello Stranger, Sign in so i know who you are !!</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <!-- Compiled and minified JavaScript -->
  </head>
  <body>
    <%= render 'partials/header' %>
    <div class="container mt-3">
      <%= render 'partials/alert' %>
      <%= yield %>
      </div>
    <%= render 'partials/footer' %>
  </body>
</html>

app/views/partials/_alert.html.erb
<%  if notice%>
<%if notice.match?(/successfully/)%>
<div class="alert alert-success alert-dismissible fade show" role="alert">
 <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<%else%>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
 <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<%end%>
 <% end %>

app/views/partials/_footer.html.erb
<footer class="page-footer" >
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
        </footer>

app/views/partials/_header.html.erb
 <nav>
    <div class="nav-wrapper">
      <%= link_to "Logo", root_path, class: "brand-logo center" %>
      <ul class="left hide-on-med-and-down">
        
        

        <% if profile_signed_in? %>
           <li><%= button_to 'Sign out',  destroy_profile_session_path, method: :delete, class: "btn btn-danger" %></li>
           <li><%= link_to 'Edit Profile',   edit_profile_registration_path, class: "btn btn-secondary" %></li>
           <li><%= link_to 'Add Friend', new_friend_path %></li>
           <li><%= link_to 'Show Friends', friends_path %></li>

         <% else %>
           <li><%= link_to 'Sign up',  new_profile_registration_path, class: "btn btn-primary" %></li>
           <li><%= link_to 'Login',  new_profile_session_path, class: "btn btn-primary" %></li>
        <% end %>

       
       
      </ul>
    </div>
  </nav>


  